Fix NPE in conditional Flyway repairs
Conditional check for `tryToMigrateIfMysql8Migration` throws NPE when run against a Spring Boot 1 database:

```log
Caused by: java.lang.NullPointerException: Cannot invoke "org.flywaydb.core.api.MigrationInfo.getVersion()" because the return value of "org.flywaydb.core.api.MigrationInfoService.current()" is null
	at com.box.l10n.mojito.FlyWayConfig.lambda$0(FlyWayConfig.java:50)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1815)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1764)
	... 16 common frames omitted
```

even though the first thrown `FlywayException` should actually be handled by `tryToMigrateIfSpringMigration`:

```log
org.flywaydb.core.api.FlywayException: Found non-empty schema(s) `mojito` but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:178)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:196)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
	at com.box.l10n.mojito.FlyWayConfig.lambda$0(FlyWayConfig.java:46)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1815)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1764)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:596)
```

This commit:
* changes order of migration attempts (SpringMigration first)
* changes conditional MySQL8 migration to first check exception text, then attempt to retrieve schema version